# Site settings
title: Pash Project
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The Pash-Project is an Open Source reimplementation of Windows PowerShell on Mono.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pash-project.github.io" # the base hostname & protocol for your site
twitter_username: PashProject
github_username:  Pash-Project

# Build settings
markdown: kramdown

kramdown:
  input: GFM
